import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LOCALES_DIR = path.join(__dirname, '../src/translations/locales');
if (!fs.existsSync(LOCALES_DIR)) {
  fs.mkdirSync(LOCALES_DIR, { recursive: true });
}

import { en } from './generateTranslations.js';

// Base dictionary loader
const translations = {};
translations.en = en;

// Helper to create language dictionary by merging with English defaults
function createLocale(baseEn, overrides) {
  return { ...baseEn, ...overrides };
}

// 1. Hindi (हिन्दी)
translations.hi = createLocale(en, {
  tagline: "तेज़। सरल। सटीक।", online: "ऑनलाइन", offline: "ऑफ़लाइन", dismiss: "खारिज करें", close: "बंद करें",
  search: "खोजें", all: "सभी", allRegions: "सभी क्षेत्र", allCategories: "सभी श्रेणियां", allTerms: "सभी शब्द",
  home: "होम", view: "देखें", delete: "हटाएं", cancel: "रद्द करें", save: "सहेजें", copy: "कॉपी करें", copied: "कॉपी हो गया!",
  linkCopied: "लिंक कॉपी हो गया!", shareResult: "परिणाम साझा करें", shareModalTitle: "स्पीड टेस्ट परिणाम साझा करें",
  copyLink: "परिणाम लिंक कॉपी करें", resetDefaults: "फ़िल्टर रीसेट करें", clearData: "डेटा साफ़ करें",
  downloadResult: "परिणाम डाउनलोड करें", exportPdf: "PDF रिपोर्ट निर्यात करें", exportCsv: "CSV निर्यात करें",
  exportJson: "JSON निर्यात करें", retest: "पुनः परीक्षण करें", testAgain: "पुनः परीक्षण करें",
  startTest: "स्पीड टेस्ट शुरू करें", stopTest: "परीक्षण रोकें", readyToTest: "परीक्षण के लिए तैयार",
  browserTested: "आपका कनेक्शन सीधे आपके ब्राउज़र से मापा जाएगा।", measurementNotice: "माप सूचना",
  telemetryVerified: "सत्यापित टेलीमेट्री", verifiedWinners: "सत्यापित विजेता", winnerClass: "विजेता वर्ग",
  time: "समय", speed: "गति", latency: "लेटेंसी", distance: "दूरी", switchNode: "नोड बदलें",
  currentlySelected: "वर्तमान में चयनित", selectServer: "सर्वर चुनें", status: "स्थिति", actions: "क्रियाएं",
  dateTime: "दिनांक और समय", date: "दिनांक", loading: "लोड हो रहा है...", details: "विवरण", readNow: "अभी पढ़ें",
  readGuide: "गाइड पढ़ें", readFullGuide: "पूरी गाइड पढ़ें", backToGuides: "सभी गाइड्स पर वापस जाएं",
  viewReport: "रिपोर्ट देखें →", loadMore: "और लोड करें", loadMoreFaqs: "और प्रश्न लोड करें",
  loadMoreRecords: "और रिकॉर्ड लोड करें", themeToggle: "थीम बदलें", settingsTooltip: "सेटिंग्स और इंजन प्राथमिकताएं",
  currentLanguage: "वर्तमान भाषा", searchLanguages: "44+ भाषाएं खोजें...", escToClose: "बंद करने के लिए ESC दबाएं",
  noLanguageFound: "कोई भाषा नहीं मिली", confirmClearHistory: "क्या आप वाकई सहेजे गए सभी टेस्ट इतिहास को हटाना चाहते हैं?",
  navSpeedTest: "स्पीड टेस्ट", navHistory: "इतिहास", navServers: "सर्वर", navDiagnostics: "डायग्नोस्टिक्स",
  navCompare: "तुलना", navFAQ: "सामान्य प्रश्न", navAbout: "हमारे बारे में", navMenu: "मेनू", navLearn: "सीखें",
  navTools: "टूल्स", navSupport: "सहायता", navContact: "संपर्क", navLegal: "सहायता और नियम", navToolsIndex: "टूल्स और सूचकांक",
  learnTag: "शिक्षा", telemetryTag: "टेलीमेट्री", governanceTag: "शासन", keyTermsTitle: "प्रमुख शब्द और शब्दावली",
  keyTermsDesc: "100+ नेटवर्किंग, बैंडविड्थ और स्पीड के बुनियादी सिद्धांत", keyTermsBadge: "100+ शब्द",
  guidesTitle: "गाइड्स और मास्टरक्लास", guidesDesc: "19 वाई-फाई, पिंग, राउटर और 5G ट्यूटोरियल", guidesBadge: "19 गाइड्स",
  directoryTitle: "प्रदर्शन निर्देशिका", directoryDesc: "वैश्विक ब्रॉडबैंड, ISP रेटिंग और टेलीमेट्री मेट्रिक्स",
  directoryBadge: "ISP टेलीमेट्री", globalIndexTitle: "ग्लोबल इंडेक्स™", globalIndexDesc: "मासिक देश रैंकिंग, औसत गति और लेटेंसी",
  globalIndexBadge: "मासिक सूचकांक", awardsTitle: "स्पीडटेस्ट अवार्ड्स™", awardsDesc: "सबसे तेज़ मोबाइल और फिक्स्ड ब्रॉडबैंड पुरस्कार",
  awardsBadge: "वार्षिक पुरस्कार", faqDesc: "नेटवर्किंग और स्पीड टेस्ट के 115+ उत्तर", faqBadge: "115+ प्रश्नोत्तर",
  aboutDesc: "कैरियर-ग्रेड टेलीमेट्री और आर्किटेक्चर", aboutBadge: "आर्किटेक्चर", privacyDesc: "शून्य लॉग और स्थानीय ब्राउज़र गोपनीयता",
  termsDesc: "उपयोग की शर्तें और सटीकता", heroBadge: "अगली पीढ़ी की नेटवर्क टेलीमेट्री", heroTitle: "अपनी इंटरनेट स्पीड जांचें",
  heroSubtitle: "कुछ ही सेकंड में डाउनलोड स्पीड, अपलोड स्पीड, पिंग, जिटर और स्थिरता मापें।",
  phaseConnecting: "सर्वश्रेष्ठ सर्वर से जुड़ रहे हैं...", phasePing: "पिंग और लेटेंसी मापी जा रही है...",
  phaseDownload: "डाउनलोड स्पीड मापी जा रही है...", phaseUpload: "अपलोड स्पीड मापी जा रही है...",
  phaseStability: "नेटवर्क स्थिरता का विश्लेषण...", phaseComplete: "परीक्षण पूरा हुआ",
  liveDownloadStream: "▼ लाइव डाउनलोड स्ट्रीम", liveUploadStream: "▲ लाइव अपलोड स्ट्रीम", probingLatency: "● पिंग लेटेंसी मापी जा रही है",
  readyForBenchmark: "परीक्षण के लिए तैयार", download: "डाउनलोड", upload: "अपलोड", ping: "पिंग", jitter: "जिटर",
  packetLoss: "पैकेट लॉस", stability: "स्थिरता", bufferbloat: "बफरब्लोट", dataUsed: "स्थानांतरित डेटा",
  networkStability: "नेटवर्क स्थिरता", excellent: "उत्कृष्ट", good: "अच्छा", fair: "औसत", poor: "कमज़ोर",
  speedMeter: "स्पीड मीटर", liveGraph: "रीयल-टाइम स्पीड ग्राफ", liveGraphSub: "समय बनाम बैंडविड्थ थ्रूपुट", connection: "कनेक्शन",
  overallRating: "समग्र नेटवर्क प्रदर्शन रेटिंग", ultraFastTitle: "अल्ट्रा-फास्ट गीगाबिट कनेक्शन",
  ultraFastDesc: "4K/8K स्ट्रीमिंग, प्रतिस्पर्धी गेमिंग और भारी नेटवर्क उपयोग के लिए सर्वोत्तम।",
  fastTitle: "उच्च-प्रदर्शन ब्रॉडबैंड", fastDesc: "4K वीडियो स्ट्रीमिंग और ज़ूम मीटिंग्स के लिए आदर्श।",
  averageTitle: "मानक ब्रॉडबैंड कनेक्शन", averageDesc: "1080p HD स्ट्रीमिंग और सामान्य वेब उपयोग के लिए उपयुक्त।",
  slowTitle: "धीमी / कमजोर लाइन", slowDesc: "सीमित बैंडविड्थ। वीडियो कॉल में बफरिंग हो सकती है।",
  tier1: "टियर 1 एंटरप्राइज", highSpeedBroadband: "हाई-स्पीड ब्रॉडबैंड", standardConnection: "मानक कनेक्शन",
  congestedSlow: "धीमा कनेक्शन", percentileText: "परीक्षण किए गए ब्रॉडबैंड कनेक्शनों के लगभग {percent}% से तेज़।",
  connectedNetwork: "कनेक्टेड नेटवर्क / ISP", serverNode: "सर्वर नोड और रूटिंग", testTimestamp: "परीक्षण समय",
  connectionInfo: "कनेक्शन जानकारी", ipAddress: "आईपी पता", isp: "आईएसपी / प्रदाता", asn: "ASN", location: "स्थान",
  timeZone: "समय क्षेत्र", device: "उपकरण", browser: "ब्राउज़र", os: "ऑपरेटिंग सिस्टम", detectingIp: "वास्तविक आईपी खोजी जा रही है...",
  detectingLocation: "स्थान खोजा जा रहा है...", exactGpsVerified: "सटीक GPS सत्यापित", liveNetworkGeo: "लाइव नेटवर्क भू-स्थान",
  detectGps: "सटीक GPS खोजें", refreshLocation: "स्थान रीफ़्रेश करें", localSystemClock: "सिस्टम घड़ी", locating: "स्थान खोज जारी है...",
  server: "सर्वर", changeServer: "सर्वर बदलें", autoServer: "स्वचालित सर्वर (निकटतम)", nearestOptimizedServer: "निकटतम अनुकूलित नोड",
  serverModalTitle: "स्पीड टेस्ट सर्वर चुनें", serverModalSubtitle: "थ्रूपुट और लेटेंसी मापने के लिए एज सर्वर चुनें।",
  searchServerPlaceholder: "शहर, देश या प्रायोजक द्वारा सर्वर खोजें...", globalRegionalServers: "वैश्विक और क्षेत्रीय स्पीड टेस्ट सर्वर",
  serversPageSubtitle: "कनेक्शन लेटेंसी और गति मापने के लिए किसी भी सर्वर को चुनें।",
  serverModalFootnote: "सर्वर उच्च-बैंडविड्थ एज बैकबोन पर होस्ट किए गए हैं। भौगोलिक रूप से निकटतम सर्वर सबसे सटीक परिणाम देता है।",
  connectionNote: "रीयल-टाइम नेटवर्क निर्देशांक और ISP रूटिंग सीधे आपके लाइव कनेक्शन से पहचानी गई हैं।",
  modernBrowser: "आधुनिक ब्राउज़र", operatingSystem: "ऑपरेटिंग सिस्टम", desktopDevice: "डेस्कटॉप डिवाइस",
  smartphoneMobile: "स्मार्टफ़ोन / मोबाइल", tabletDevice: "टैबलेट डिवाइस", html5ModernClient: "HTML5 आधुनिक क्लाइंट",
  broadbandIsp: "ब्रॉडबैंड आईएसपी", countryIndia: "भारत", compareTitle: "अपनी गति की तुलना करें",
  compareSubtitle: "स्ट्रीमिंग, गेमिंग, वीडियो कॉल और डाउनलोड के लिए अपनी गति को वैश्विक मानकों से मापें।",
  activityStreaming: "4K UHD स्ट्रीमिंग", streamingDesc: "नेटफ्लिक्स, यूट्यूब और प्राइम वीडियो पर बिना रुके वीडियो प्लेबैक",
  activityGaming: "प्रतिस्पर्धी ऑनलाइन गेमिंग", gamingDesc: "बेहतर मल्टीप्लेयर गेमिंग के लिए अल्ट्रा-कम लेटेंसी और न्यूनतम जिटर",
  activityZoom: "ज़ूम और वीडियो कॉल", zoomDesc: "बिना रुके उच्च गुणवत्ता वाली HD ऑडियो और वीडियो कॉल",
  activityDownloads: "बड़ी फ़ाइल डाउनलोड", downloadsDesc: "गेम्स, ओएस अपडेट और बैकअप के लिए तेज़ डाउनलोड स्पीड",
  seamless: "निर्बाध", ultraLowPing: "अल्ट्रा-लो पिंग", studioQuality: "स्टूडियो गुणवत्ता", lightningFast: "अत्यंत तेज़",
  yourSpeed: "आपकी गति", avgSpeed: "वैश्विक औसत", reqStreaming: "25+ Mbps डाउनलोड", reqGaming: "< 35ms पिंग और कम जिटर",
  reqZoom: "5+ Mbps अपलोड और डाउनलोड", reqDownloads: "25+ Mbps अपलोड", diagnosticsTitle: "नेटवर्क डायग्नोस्टिक्स",
  diagnosticsSubtitle: "रीयल-टाइम ब्राउज़र सॉकेट और टेलीमेट्री अखंडता जांच", runDiagnostics: "डायग्नोस्टिक्स चलाएं",
  runningDiagnostics: "सॉकेट पाइपलाइन जांची जा रही है...", testGateway: "इंटरनेट गेटवे कनेक्टिविटी",
  testGatewayDesc: "संपूर्ण एंड-टू-एंड आईपी नेटवर्क गेटवे उपलब्ध है।", testHttp: "HTTP एज लेटेंसी और DNS लुकअप",
  testHttpDesc: "निकटतम सर्वर के साथ तीव्र sub-50ms हैंडशेक।", testJitter: "पैकेट टाइमिंग और जिटर विचरण",
  testJitterDesc: "न्यूनतम जिटर के साथ स्थिर पैकेट वितरण समय।", testSecurity: "ट्रांसपोर्ट लेयर सिक्योरिटी (TLS/HTTPS)",
  testSecurityDesc: "सभी नेटवर्क डेटा के लिए सुरक्षित टीएलएस एन्क्रिप्शन सक्रिय है।", testBufferbloat: "बफरब्लोट और कतारबद्धता देरी",
  testBufferbloatDesc: "कम बफरब्लोट। भारी नेटवर्क लोड के दौरान भी लेटेंसी स्थिर रहती है।", testHistory: "परीक्षण इतिहास",
  testHistorySubtitle: "स्थानीय रूप से सहेजे गए स्पीड टेस्ट और लेटेंसी बेंचमार्क।",
  noHistory: "अभी कोई इतिहास नहीं है। परिणाम सहेजने के लिए स्पीड टेस्ट चलाएं।", clearHistory: "इतिहास साफ़ करें",
  searchHistoryPlaceholder: "इतिहास खोजें (आईएसपी, सर्वर, तारीख)...", viewCertificate: "विवरण / प्रमाणपत्र देखें",
  downloadPdfReport: "PDF रिपोर्ट डाउनलोड करें", deleteRecord: "रिकॉर्ड हटाएं", settings: "सेटिंग्स",
  settingsSubtitle: "स्पीड टेस्ट इंजन कॉन्फ़िगरेशन", theme: "थीम", dark: "डार्क", light: "लाइट", units: "स्पीड यूनिट",
  duration: "परीक्षण अवधि", quick: "त्वरित (5s)", standard: "मानक (10s)", extended: "विस्तृत (20s)",
  parallelStreams: "समानांतर मल्टी-स्ट्रीम", saveHistoryToggle: "स्थानीय रूप से इतिहास सहेजें",
  dataWarning: "स्पीड टेस्ट वास्तविक डेटा ट्रांसफर करता है (बैंडविड्थ के आधार पर ~20MB से ~300MB)।",
  streamSingular: "1 स्ट्रीम", streamsPlural: "{n} स्ट्रीम", glossaryPill: "नेटवर्क और स्पीड विश्वकोश",
  keyTermsMainTitle: "प्रमुख इंटरनेट और नेटवर्किंग शब्द",
  keyTermsMainLead: "100+ नेटवर्किंग, ब्रॉडबैंड, वाई-फाई, 5G और टेलीमेट्री बेंचमार्क अवधारणाओं का व्यापक विश्वकोश।",
  keyTermsSubtitle: "100+ ब्रॉडबैंड, वाई-फाई, लेटेंसी और स्पीड टेस्ट अवधारणाओं की विस्तृत मार्गदर्शिका।",
  searchKeyTermsPlaceholder: "100+ शब्द खोजें (उदा. बफरब्लोट, वाई-फाई 7, जिटर)...",
  glossarySearchPlaceholder: "100+ शब्द खोजें (उदा. Bufferbloat, Wi-Fi 7, Jitter)...", simpleDefinition: "सरल परिभाषा",
  detailedExplanation: "विस्तृत तकनीकी विश्लेषण", technicalBreakdown: "तकनीकी विश्लेषण", whyItMatters: "यह क्यों महत्वपूर्ण है",
  realWorldExample: "वास्तविक उदाहरण", relatedTerms: "संबंधित शब्द", showingTerms: "कुल {total} में से {count} शब्द दिखाए जा रहे हैं",
  noTermsFound: "कोई मेल खाता शब्द नहीं मिला", trySearchingDifferent: "कोई दूसरा कीवर्ड खोजने या फ़िल्टर रीसेट करने का प्रयास करें।",
  guidesPill: "स्पीड और नेटवर्क मास्टरक्लास", guidesMainTitle: "ब्रॉडबैंड, वाई-फाई और पिंग अनुकूलन गाइड्स",
  guidesMainLead: "पिंग कम करने, बफरब्लोट दूर करने, वाई-फाई चैनल अनुकूलित करने और गति बढ़ाने पर 19 विस्तृत मास्टरक्लास।",
  searchGuidesPlaceholder: "19 मास्टरक्लास खोजें...", featuredGuide: "विशेष गाइड",
  showingGuides: "कुल {total} में से {count} गाइड्स दिखाई जा रही हैं", guideIntro: "1. परिचय",
  guideExplanation: "2. विस्तृत तकनीकी व्याख्या", guideSteps: "3. चरण-दर-चरण निर्देश", guideTips: "4. विशेषज्ञ प्रो टिप्स",
  guideMistakes: "5. सामान्य गलतियां जिनसे बचें", guideConclusion: "6. मुख्य निष्कर्ष और सारांश", tipPrefix: "टिप",
  mistakePrefix: "गलती", foundHelpful: "क्या यह गाइड उपयोगी लगी?", directoryPill: "वैश्विक ISP और नेटवर्क बेंचमार्क",
  performanceDirectoryTitle: "स्पीडटेस्ट प्रदर्शन निर्देशिका",
  directoryMainLead: "दुनिया भर के प्रमुख फाइबर, केबल और 5G प्रदाताओं की औसत गति, लेटेंसी और टेलीमेट्री देखें।",
  searchIspPlaceholder: "नाम, देश या तकनीक द्वारा ISP खोजें...", directorySearchPlaceholder: "नाम, देश या तकनीक द्वारा ISP खोजें...",
  coreMetricsExplained: "प्रमुख टेलीमेट्री मेट्रिक्स की व्याख्या", benchmarkLabel: "मानक बेंचमार्क:",
  ispCarrierIndex: "ISP और नेटवर्क प्रदर्शन सूचकांक",
  ispCarrierSubtitle: "उपभोक्ता परीक्षणों से एकत्रित सत्यापित थ्रूपुट और लेटेंसी मेट्रिक्स",
  recommendedChecklist: "100% सटीक परीक्षण के लिए अनुशंसित चेकलिस्ट", providerCol: "प्रदाता और क्षेत्र", techCol: "तकनीक",
  globalIndexPill: "वैश्विक गति रैंकिंग", globalIndexMainTitle: "स्पीडटेस्ट ग्लोबल इंडेक्स™",
  globalIndexMainLead: "दुनिया भर के देशों में फिक्स्ड ब्रॉडबैंड और मोबाइल इंटरनेट गति की मासिक रैंकिंग।",
  searchCountryPlaceholder: "देश या क्षेत्र खोजें...", globalIndexSearchPlaceholder: "देश या क्षेत्र खोजें...",
  medianDownload: "औसत डाउनलोड", medianUpload: "औसत अपलोड", medianLatency: "औसत लेटेंसी", fixedBroadband: "फिक्स्ड ब्रॉडबैंड",
  mobileData: "मोबाइल 5G", fastestCities: "सबसे तेज़ बेंचमार्क शहर", leadingOperator: "अग्रणी नेटवर्क ऑपरेटर",
  leadingOperatorDesc: "{isp} वर्तमान में {country} में सबसे तेज़ नेटवर्क मापा गया है।",
  methodologyTitle: "इंडेक्स गणना कार्यप्रणाली",
  methodologyDesc: "स्पीडटेस्ट ग्लोबल इंडेक्स™ हर महीने लाखों सक्रिय उपभोक्ता गति बेंचमार्क का विश्लेषण करता है।",
  awardsPill: "सत्यापित प्रदर्शन उत्कृष्टता", speedtestAwardsTitle: "स्पीडटेस्ट अवार्ड्स™",
  awardsMainLead: "उत्कृष्ट गति, अल्ट्रा-लो लेटेंसी और स्थिरता के लिए दुनिया के शीर्ष इंटरनेट प्रदाताओं को सम्मान।",
  eligibilityStandard: "पात्रता मानक:", awardCategoriesWinners: "पुरस्कार श्रेणियां और विजेता", runnerUp: "उपविजेता:",
  awardsArchive: "स्पीडटेस्ट अवार्ड्स™ पुरालेख", awardsFaqTitle: "पुरस्कारों के बारे में अक्सर पूछे जाने वाले प्रश्न",
  topFixed: "शीर्ष फिक्स्ड", topMobile: "शीर्ष मोबाइल", topGaming: "शीर्ष गेमिंग", faqPill: "ज्ञानकोश और अक्सर पूछे जाने वाले प्रश्न",
  faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
  faqSubtitle: "इंटरनेट की गति, लेटेंसी, जिटर, वाई-फाई और नेटवर्क डायग्नोस्टिक्स के बारे में सब कुछ।",
  searchFaqPlaceholder: "115+ प्रश्न खोजें...", noQuestionsFound: "आपकी खोज से मेल खाता कोई प्रश्न नहीं मिला",
  catBasics: "गति की मूल बातें", catSpeedBasics: "गति की मूल बातें", catPingLatency: "पिंग और लेटेंसी", catWifiRouters: "वाई-फाई और राउटर",
  catFiberBroadband: "फाइबर और ब्रॉडबैंड", cat5gMobile: "5G और मोबाइल", catGamingEsports: "गेमिंग और ई-स्पोर्ट्स",
  catStreamingWork: "स्ट्रीमिंग और वर्क", catHardwareCables: "हार्डवेयर और केबल", catDnsVpnSecurity: "DNS, VPN और सुरक्षा",
  aboutTitle: "NETSPEEDPRO के बारे में", aboutSubtitle: "पारदर्शी इंजीनियरिंग और नेटवर्क मापन मानक",
  aboutLead: "NETSPEEDPRO एक अत्यधिक सटीक, ब्राउज़र-आधारित इंटरनेट स्पीड और ब्रॉडबैंड डायग्नोस्टिक्स प्लेटफ़ॉर्म है।",
  founderBadge: "✦ संस्थापक और मुख्य वास्तुकार", founderTitle: "संस्थापक और मुख्य वास्तुकार", founderName: "मोहम्मद रहमत अंसारी",
  founderDesc: "विश्व स्तर पर पारदर्शी, उच्च-सटीक और कैरियर-ग्रेड नेटवर्क उपकरण बनाने के लिए समर्पित।",
  founderLead: "विश्व स्तर पर पारदर्शी, उच्च-सटीक और कैरियर-ग्रेड नेटवर्क उपकरण बनाने के लिए समर्पित।",
  linkedinProfile: "लिंक्डइन प्रोफ़ाइल", multiStreamArch: "मल्टी-स्ट्रीम आर्किटेक्चर",
  multiStreamArchDesc: "हाई-स्पीड फाइबर और मल्टी-गीगाबिट कनेक्शन को पूरी तरह से मापने के लिए कई समानांतर वर्कर का उपयोग करता है।",
  subMilliTelemetry: "सब-मिलीसेकंड टेलीमेट्री",
  subMilliTelemetryDesc: "माइक्रोसेकंड पिंग और जिटर गणना के लिए उच्च-रिज़ॉल्यूशन टाइमर का लाभ उठाता है।",
  privacyFirstTitle: "जीरो-लॉग गोपनीयता",
  privacyFirstDesc: "कोई ट्रैकिंग पिक्सेल नहीं, कोई तृतीय-पक्ष स्क्रिप्ट नहीं, और उपयोगकर्ता डेटा कभी नहीं बेचा जाता।",
  carrierGradeTitle: "कैरियर-ग्रेड अंशांकन",
  carrierGradeDesc: "फाइबर, वाई-फाई 7 और 5G के लिए आधुनिक दूरसंचार मानकों के अनुसार इंजीनियर।",
  effectiveDate: "प्रभावी तिथि: जनवरी 2026 | संस्करण 1.0", privacyTitle: "गोपनीयता नीति",
  privacySubtitle: "प्रभावी तिथि: जनवरी 2026 | संस्करण 1.0", privacyCommitmentTitle: "1. हमारी गोपनीयता प्रतिबद्धता",
  privacyCommitmentText: "NETSPEEDPRO में हम मानते हैं कि स्पीड टेस्ट तेज़, सटीक और आपकी गोपनीयता का सम्मान करने वाला होना चाहिए। हम आपका डेटा कभी नहीं बेचते हैं।",
  privacyProcessedTitle: "2. परीक्षण के दौरान संसाधित जानकारी",
  privacyProcessedText: "जब आप स्पीड टेस्ट शुरू करते हैं, तो सटीक माप के लिए केवल आवश्यक तकनीकी टेलीमेट्री संसाधित की जाती है:",
  privacyProcessedItem1: "सार्वजनिक आईपी और ASN: आईएसपी नाम निर्धारित करने और निकटतम सर्वर का चयन करने के लिए।",
  privacyProcessedItem2: "थ्रूपुट मेट्रिक्स: स्थानांतरित बाइट्स, बीता समय और पिंग टाइमस्टैम्प।",
  privacyProcessedItem3: "ब्राउज़र यूजर-एजेंट: मल्टी-स्ट्रीम कॉन्फ़िगरेशन को अनुकूलित करने के लिए।",
  privacyStorageTitle: "3. परीक्षण इतिहास का स्थानीय संग्रहण",
  privacyStorageText: "आपका स्पीड टेस्ट इतिहास केवल आपके ब्राउज़र के localStorage में संग्रहीत होता है। आपके पास इसे कभी भी हटाने का पूरा नियंत्रण है।",
  privacySecurityTitle: "4. सुरक्षा और एन्क्रिप्शन",
  privacySecurityText: "सभी डेटा प्रसारण पारगमन में छेड़छाड़ को रोकने के लिए मानक HTTPS/TLS एन्क्रिप्शन का उपयोग करते हैं।",
  privacyContactTitle: "5. संपर्क और पूछताछ",
  privacyContactText: "यदि आपके पास कोई प्रश्न है, तो कृपया मुख्य वास्तुकार मोहम्मद रहमत अंसारी से संपर्क करें।",
  termsTitle: "उपयोग की शर्तें", termsSubtitle: "उपयोग की शर्तें और स्वीकार्य नेटवर्क परीक्षण",
  termsAcceptanceTitle: "1. शर्तों की स्वीकृति", termsAcceptanceText: "NETSPEEDPRO का उपयोग करके, आप इन सेवा की शर्तों से सहमत होते हैं।",
  termsUsageTitle: "2. स्वीकार्य नेटवर्क उपयोग", termsUsageText: "NETSPEEDPRO व्यक्तिगत और उद्यम गति परीक्षण के लिए है। अनधिकृत तनाव परीक्षण प्रतिबंधित है।",
  termsAccuracyTitle: "3. मापन सटीकता और अस्वीकरण",
  termsAccuracyText: "परिणाम सूचनात्मक और समस्या निवारण उद्देश्यों के लिए प्रदान किए जाते हैं।",
  termsContactTitle: "4. संपर्क जानकारी", termsContactText: "पूछताछ के लिए सीधे संपर्क करें:",
  footerTagline: "तेज़। सरल। सटीक।",
  footerDesc: "वास्तविक ब्राउज़र-आधारित नेटवर्क स्ट्रीमिंग टेलीमेट्री द्वारा संचालित पेशेवर डायग्नोस्टिक सूट।",
  footerFiberNote: "हाई-स्पीड फाइबर, 5G और मल्टी-गीगाबिट कनेक्शन के लिए निर्मित।",
  footerCopyright: "© 2026 NETSPEEDPRO. सर्वाधिकार सुरक्षित। मोहम्मद रहमत अंसारी द्वारा डिज़ाइन और इंजीनियर।",
  learn: "सीखें", tools: "टूल्स", support: "सहायता", contact: "संपर्क"
});

console.log('Writing locales to files...');
